/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package senacbankpoo.ui;

import javax.swing.JFrame;
import senacbankpoo.ui.caixa.TelaCaixaCorrente;
import senacbankpoo.ui.caixa.TelaDeposito;
import senacbankpoo.ui.caixa.TelaLoginCorrente;
import senacbankpoo.ui.clientes.TelaConsultarPessoasFisicas;
import senacbankpoo.ui.contas.TelaConsultarContasCorrente;

/**
 *
 * @author Beto
 */
public class Home extends javax.swing.JFrame {

    private TelaConsultarPessoasFisicas telaConsultarPessoasFisicas = null;

    private TelaConsultarContasCorrente telaConsultarContasCorrente = null;
    
    private TelaDeposito telaDeposito = null;

    private TelaLoginCorrente telaLogin = null;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuDeposito = new javax.swing.JMenuItem();
        menuLoginContaCorrente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Clientes");

        jMenuItem1.setText("Gereneciador Pessoa Fisica");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Contas");

        jMenuItem3.setText("Gerenciar Contas Correntes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Caixa Eletronico");

        menuDeposito.setText("Deposito");
        menuDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepositoActionPerformed(evt);
            }
        });
        jMenu3.add(menuDeposito);

        menuLoginContaCorrente.setText("Login Conta Corrente");
        menuLoginContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginContaCorrenteActionPerformed(evt);
            }
        });
        jMenu3.add(menuLoginContaCorrente);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (telaConsultarPessoasFisicas == null || !telaConsultarPessoasFisicas.isDisplayable()) {
            telaConsultarPessoasFisicas = new TelaConsultarPessoasFisicas();
            telaConsultarPessoasFisicas.pack();
            telaConsultarPessoasFisicas.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            telaConsultarPessoasFisicas.setLocationRelativeTo(null);
            telaConsultarPessoasFisicas.setVisible(true);
        }
        telaConsultarPessoasFisicas.toFront();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (telaConsultarContasCorrente == null || !telaConsultarContasCorrente.isDisplayable()) {
            telaConsultarContasCorrente = new TelaConsultarContasCorrente();
            telaConsultarContasCorrente.pack();
            telaConsultarContasCorrente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            telaConsultarContasCorrente.setLocationRelativeTo(null);
            telaConsultarContasCorrente.setVisible(true);
        }
        telaConsultarContasCorrente.toFront();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepositoActionPerformed
        if (telaDeposito == null || !telaDeposito.isDisplayable()) {
            telaDeposito = new TelaDeposito();
            telaDeposito.pack();
            telaDeposito.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            telaDeposito.setLocationRelativeTo(null);
            telaDeposito.setVisible(true);
        }
        telaDeposito.toFront();
    }//GEN-LAST:event_menuDepositoActionPerformed

    private void menuLoginContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginContaCorrenteActionPerformed
if (telaLogin == null || !telaLogin.isDisplayable()) {
            telaLogin = new TelaLoginCorrente();
            telaLogin.pack();
            telaLogin.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            telaLogin.setLocationRelativeTo(null);
            telaLogin.setVisible(true);
        }
        telaLogin.toFront();
    }//GEN-LAST:event_menuLoginContaCorrenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menuDeposito;
    private javax.swing.JMenuItem menuLoginContaCorrente;
    // End of variables declaration//GEN-END:variables
}
